#!/bin/bash
#
# ** nextcloud_backups_aws_s3 **
# Utility to make backups of Nextcloud and store them in an S3 bucket
#
# Álvaro Castellano Vela - https://github.com/a-castellano

# Option variables
ENABLE_LOG=false # by default this script write logs via syslog

# Default values
NEXTCLOUD_DIR='/var/www/nextcloud'

# Nextcloud variables
NEXTCLOUD_CONFIG_SUBDIR='/config/config.php'

# Log variables
LOGGET_TAG="nextcloud_backups_aws_s3"
LOGGER="$(which logger) -t $LOGGET_TAG"

# Functions

function trim {
    echo $1 | sed 's/^--//'
}

function report_error {
    error_message="Error: $@"
    stderr=""
    if [[ -z "$SILENT" || "$SILENT" = false ]]; then
       stderr="--stderr"
    fi
    $LOGGER $stderr $error_message
}

function check_option_called {
    option_called="_OPTION_CALLED"
    option_name=$1
    variable_name=$(echo $option_name | tr '[:lower:]' '[:upper:]' | tr '-' '_')
    variable_called_name="$variable_name$option_called"
    if [[ -z ${!variable_called_name} || "${!variable_called_name}" = false  ]]; then
        if [ "$#" -eq 1 ]; then
            eval $variable_name=true
        fi
        if [ "$#" -eq 2 ]; then
            eval $variable_name=$2
            if [ -z "$variable_name" ]; then
                error_msg="$variable_name was supposed to be set. Can't parse '$2'."
                report_error $error_msg
                exit 1
            fi
        fi
        eval $variable_called_name=true
    else
        error_msg="It is not allowed to set $option_name options more than two times."
        report_error $error_msg
        exit 1
    fi
}

# Main

OPTS=`getopt -o vhns --long verbose,dry-run,help,silent,s3-access-key:,s3-secret-key:,database-name:,database-user:,database-passwd:,database-host:,database-port: -n 'parse-options' -- "$@" 2> .error.log `

if [ $? -ne 0 ]; then
    error_msg=$(cat .error.log)
    $(which rm) .error.log
    report_error $error_msg
    exit 1
fi

echo "$OPTS"
eval set -- "$OPTS"


while true; do
  case "$1" in
    -s | --silent )
            check_option_called 'silent'
            shift ;;
    -v | --verbose )
            check_option_called 'verbose'
            shift ;;
    -h | --help )
            check_option_called 'help'
            shift ;;
    -n | --dry-run )
            check_option_called 'dry-run'
            shift ;;
    --s3-access-key )
            check_option_called $( trim $1 ) $2
            shift ; shift;;
    --s3-secret-key )
            check_option_called $( trim $1 ) $2
            shift ; shift;;
    --database-name )
            check_option_called $( trim $1 ) $2
            shift ; shift;;
    --database-user )
            check_option_called $( trim $1 ) $2
            shift ; shift;;
    --database-passwd )
            check_option_called $( trim $1 ) $2
            shift ; shift;;
    --database-host )
            check_option_called $( echo $1 | sed 's/^--//' ) $2
            shift ; shift;;
    --database-port )
            check_option_called $( echo $1 | sed 's/^--//' ) $2
            shift ; shift;;

    -s | --stack-size ) STACK_SIZE="$2"; shift; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

echo "---END"

echo VERBOSE=$VERBOSE
echo HELP=$HELP
echo DRY_RUN=$DRY_RUN
echo S3_ACCESS_KEY=$S3_ACCESS_KEY
echo S3_SECRET_KEY=$S3_SECRET_KEY
echo DATABASE_PORT=$DATABASE_PORT
