#!/usr/bin/env bash
# file: tests/02-usage

source lib/99-clean_variables.sh

oneTimeSetUp() {
    export NEXTCLOUD_PATH="$(pwd)/tests/config_folders/config_test"
    export CONFIG_FILE="$(pwd)/tests/config_folders/config/nextcloud_backups_aws_s3"
    export TMP_FOLDER="/var/tmp/nextcloud_backups_aws_s3/tests"
    mkdir -p $TMP_FOLDER
}

oneTimeTearDown() {
    unset NEXTCLOUD_PATH
    unset CONFIG_FILE
    cleanVariables
    rm -rf $TMP_FOLDER/*
}

testUsage() {
    ./nextcloud_backups_aws_s3 -u > /dev/null
    ok=$?
    assertEquals "$ok" "0"
}

testUnregisteredOptions() {
   cat << EOF > $TMP_FOLDER/expectedError
Error: parse-options: unrecognized option '--nonsene'
EOF
    ./nextcloud_backups_aws_s3 -s --test='undefined-variable, something' --nonsene  2> $TMP_FOLDER/error
    sed  's/^.*nextcloud_backups_aws_s3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?
    assertEquals $match 0
}

testNoLogFile() {
   cat << EOF > $TMP_FOLDER/expectedError
Error: Log enabled but there is no log file declared, add '--log-file' option.
EOF
    ./nextcloud_backups_aws_s3 -l 2> $TMP_FOLDER/error
    sed  's/^.*nextcloud_backups_aws_s3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?
    assertEquals $match 0
}

testFailToCreateLogPermission() {
   mkdir -p $TMP_FOLDER/nopermissionfolder/
   touch $TMP_FOLDER/nopermissionfolder/nextcloud_backups_aws_s3.log
   chmod 400 $TMP_FOLDER/nopermissionfolder/nextcloud_backups_aws_s3.log
   cat << EOF > $TMP_FOLDER/expectedError
Error: Cannot write log in '$TMP_FOLDER/nopermissionfolder/nextcloud_backups_aws_s3.log': Permission Denied
EOF
    ./nextcloud_backups_aws_s3 -l --log-file="$TMP_FOLDER/nopermissionfolder/nextcloud_backups_aws_s3.log" 2> $TMP_FOLDER/error
    sed  's/^.*nextcloud_backups_aws_s3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?
    assertEquals $match 0
}

testFailToCreateLogPathDoesNotExist() {
#   rm -rf $TMP_FOLDER/nonexistentfolder
   cat << EOF > $TMP_FOLDER/expectedError
Error: Cannot write log in '$TMP_FOLDER/nonexistentfolder': Given path does not exist
EOF
    ./nextcloud_backups_aws_s3 -l --log-file="$TMP_FOLDER/nonexistentfolder/nextcloud_backups_aws_s3.log" 2> $TMP_FOLDER/error
    sed  's/^.*nextcloud_backups_aws_s3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?
    assertEquals $match 0
}


# Load shUnit2.
. /usr/bin/shunit2
