#!/usr/bin/env bash
# file: tests/03-configfiles

source lib/99-clean_variables.sh

setUp(){
    export TMP_FOLDER="/var/tmp/nextcloud_backups_aws_s3/tests"
    mkdir -p $TMP_FOLDER
}

oneTimeSetUp() {
    cleanVariables
    export NEXTCLOUD_PATH="$(pwd)/tests/config_folders/config_test"
    export CONFIG_FILE="$(pwd)/tests/config_folders/config/nextcloud_backups_aws_s3"
    export TMP_FOLDER="/var/tmp/nextcloud_backups_aws_s3/tests"
    mkdir -p $TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud/config
    cat << EOF > $TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud/config/config.php
<?php
$CONFIG = array (
  'instanceid' => 'test',
  'passwordsalt' => 'test',
  'secret' => 'test',
  'trusted_domains' =>
  array (
    0 => 'test',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'test',
  'dbtype' => 'mysql',
  'version' => 'test',
  'dbname' => 'mydb',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbuser',
  'dbpassword' => 'mypassowd',
  'installed' => true,
  'memcache.local' => 'test',
  'memcache.distributed' => 'test',
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'no-reply',
  'mail_domain' => 'test',
  'mail_smtphost' => 'test',
  'mail_smtpport' => '1000000',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'test',
  'mail_smtppassword' => 'test',
  'mail_smtpsecure' => 'ssl',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);
EOF
}

oneTimeTearDown() {
    cleanVariables
    rm -rf $TMP_FOLDER/nextcloud_backups_aws_s3
}

testConfigDirDefault() {
    default=$(./nextcloud_backups_aws_s3 --test='config-file' --nextcloud-path="$TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud" )
    assertEquals "$default" "CONFIG_FILE -> $(pwd)/tests/config_folders/config/nextcloud_backups_aws_s3"
}

testConfigFileDoesNotExist() {
    rm -f $TMP_FOLDER/none
    ./nextcloud_backups_aws_s3 --nextcloud-path="$TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud" --config-file="/tmp/none" 2> /dev/null
    ok=$?
    assertEquals "$ok" "1"
    rm -f $TMP_FOLDER/none
}

testConfigFileDoesNotExistCheckFile() {
    rm -f $TMP_FOLDER/none
    cat << EOF > $TMP_FOLDER/fileDoesNotExistError
Error: Config file '$TMP_FOLDER/none' does not exist.
EOF
   ./nextcloud_backups_aws_s3 --config-file="$TMP_FOLDER/none" --nextcloud-path="$TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud" 2> $TMP_FOLDER/error
   sed  's/^.*nextcloud_backups_aws_s3: //' -i $TMP_FOLDER/error
   diff $TMP_FOLDER/fileDoesNotExistError $TMP_FOLDER/error
   match=$?
   assertEquals "$match" "0"
   rm -f $TMP_FOLDER/none $TMP_FOLDER/fileDoesNotExistError $TMP_FOLDER/error
}

testGetVariablesFromFile() {
    rm -f $TMP_FOLDER/variables $TMP_FOLDER/testMultipleValues $TMP_FOLDER/testMultipleValuesResult

    cat << EOF > $TMP_FOLDER/variables
S3_ACCESS_KEY=MyAccesKey
S3_SECRET_KEY=MySecretKey
DATABASE_NAME=MyDatabase
DATABASE_USER=MyUser
DATABASE_PASSWD="Pass word"
EOF

    cat << EOF > $TMP_FOLDER/testMultipleValues
S3_ACCESS_KEY -> MyAccesKey
S3_SECRET_KEY -> MySecretKey
NEXTCLOUD_USERS -> ALL
DATABASE_NAME -> MyDatabase
DATABASE_PASSWD -> Pass word
EOF

   ./nextcloud_backups_aws_s3  --config-file="$TMP_FOLDER/variables" --test="s3-access-key,s3-secret-key,nextcloud-users,database-name,database-passwd" --nextcloud-path="$TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud" > $TMP_FOLDER/testMultipleValuesResult
   diff  $TMP_FOLDER/testMultipleValuesResult $TMP_FOLDER/testMultipleValues
   match=$?
   assertEquals "$match" "0"
   rm -f /tmp/variables $TMP_FOLDER/testMultipleValues $TMP_FOLDER/testMultipleValuesResult
}

testGetVariablesFromNexcloudconfig() {
    rm -f $TMP_FOLDER/testMultipleValues $TMP_FOLDER/testMultipleValuesResult

    cat << EOF > $TMP_FOLDER/variables
S3_ACCESS_KEY=MyAccesKey
S3_SECRET_KEY=MySecretKey
EOF

    cat << EOF > $TMP_FOLDER/testMultipleValues
S3_ACCESS_KEY -> MyAccesKey
S3_SECRET_KEY -> MySecretKey
NEXTCLOUD_USERS -> ALL
DATABASE_NAME -> mydb
DATABASE_PASSWD -> mypassowd
DATABASE_PORT -> 3306
DATABASE_USER -> dbuser
DATABASE_HOST -> localhost
EOF

   ./nextcloud_backups_aws_s3  --config-file="$TMP_FOLDER/variables" --test="s3-access-key,s3-secret-key,nextcloud-users,database-name,database-passwd,database-port,database-user,database-host" --nextcloud-path="$TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud" > $TMP_FOLDER/testMultipleValuesResult
   diff  $TMP_FOLDER/testMultipleValuesResult $TMP_FOLDER/testMultipleValues
   match=$?
   assertEquals "$match" "0"
   rm -f $TMP_FOLDER/variables $TMP_FOLDER/testMultipleValues $TMP_FOLDER/testMultipleValuesResult
}

testGetVariablesFromNexcloudconfigAndReplaceWithConfig() {
    rm -f $TMP_FOLDER/testMultipleValues $TMP_FOLDER/testMultipleValuesResult

    cat << EOF > $TMP_FOLDER/variables
S3_ACCESS_KEY=MyAccesKey
S3_SECRET_KEY=MySecretKey
DATABASE_NAME=mychangeddbname
EOF

    cat << EOF > $TMP_FOLDER/testMultipleValues
S3_ACCESS_KEY -> MyAccesKey
S3_SECRET_KEY -> MySecretKey
DATABASE_NAME -> mychangeddbname
DATABASE_PASSWD -> mypassowd
DATABASE_PORT -> 3306
DATABASE_USER -> dbuser
DATABASE_HOST -> localhost
NEXTCLOUD_USERS -> ALL
EOF

   ./nextcloud_backups_aws_s3  --config-file="$TMP_FOLDER/variables" --test="s3-access-key,s3-secret-key,database-name,database-passwd,database-port,database-user,database-host,nextcloud-users" --nextcloud-path="$TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud" > $TMP_FOLDER/testMultipleValuesResult
   diff  $TMP_FOLDER/testMultipleValuesResult $TMP_FOLDER/testMultipleValues
   match=$?
   assertEquals "$match" "0"
   rm -f $TMP_FOLDER/variables $TMP_FOLDER/testMultipleValues $TMP_FOLDER/testMultipleValuesResult
}

testGetVariablesFromNexcloudconfigAndReplaceInCommandLine() {
    rm -f $TMP_FOLDER/testMultipleValues $TMP_FOLDER/testMultipleValuesResult

    cat << EOF > $TMP_FOLDER/variables
S3_ACCESS_KEY=MyAccesKey
S3_SECRET_KEY=MySecretKey
DATABASE_NAME=mychangeddbname
DATABASE_PASSWD=mypassorwd
EOF

    cat << EOF > $TMP_FOLDER/testMultipleValues
S3_ACCESS_KEY -> MyAccesKey
S3_SECRET_KEY -> MyChangedSecretKey
DATABASE_NAME -> mychangeddbname
DATABASE_PASSWD -> mypassorwd
DATABASE_PORT -> 3307
DATABASE_USER -> dbuser
DATABASE_HOST -> 127.0.0.1
NEXTCLOUD_USERS -> ALL
EOF

   ./nextcloud_backups_aws_s3 --s3-secret-key="MyChangedSecretKey" --database-port=3307 --database-host="127.0.0.1" --config-file="$TMP_FOLDER/variables" --test="s3-access-key,s3-secret-key,database-name,database-passwd,database-port,database-user,database-host,nextcloud-users" --nextcloud-path="$TMP_FOLDER/nextcloud_backups_aws_s3/var/www/nextcloud" > $TMP_FOLDER/testMultipleValuesResult
   diff  $TMP_FOLDER/testMultipleValuesResult $TMP_FOLDER/testMultipleValues
   match=$?
   assertEquals "$match" "0"
   rm -f $TMP_FOLDER/variables $TMP_FOLDER/testMultipleValues $TMP_FOLDER/testMultipleValuesResult
}


# Load shUnit2.
. /usr/bin/shunit2
