#!/bin/sh
# file: tests/04-unsetvariables

oneTimeSetUp() {
    export NEXTCLOUD_PATH="$(pwd)/tests/config_folders/config_test_no_values"
    export CONFIG_FILE="$(pwd)/tests/config_folders/config/nextcloud_backups_aws_s3"
}

testFailNoDatabaseVariables() {
   rm -f /tmp/variables /tmp/expectedError /tmp/error
   cat << EOF > /tmp/variables
S3_ACCESS_KEY=MyAccesKey
S3_SECRET_KEY=MySecretKey
EOF

   cat << EOF > /tmp/expectedError
Error: The following variables has to have value: database-name, database-user, database-passwd. Please set a valid value for it.
EOF
    ./nextcloud_backups_aws_s3  --config-file="/tmp/variables" 2> /tmp/error > /dev/null
    sed  's/^.*nextcloud_backups_aws_s3: //' -i /tmp/error
    diff /tmp/expectedError /tmp/error
    match=$?
    assertEquals "$match" "0"
    rm -f /tmp/variables /tmp/expectedError /tmp/error
}

testFailNoS3Variables() {
   rm -f /tmp/variables /tmp/expectedError /tmp/error
   cat << EOF > /tmp/variables
DATABASE_NAME=dbname
DATABASE_USER=dbuser
DATABASE_PASSWD=mysecret
DATABASE_PORT=3307
DATABASE_HOST=localhost
EOF

   cat << EOF > /tmp/expectedError
Error: The following variables has to have value: s3-access-key, s3-secret-key. Please set a valid value for it.
EOF
    ./nextcloud_backups_aws_s3  --config-file="/tmp/variables" 2> /tmp/error > /dev/null
    sed  's/^.*nextcloud_backups_aws_s3: //' -i /tmp/error
    diff /tmp/expectedError /tmp/error
    match=$?
    assertEquals "$match" "0"
    rm -f /tmp/variables /tmp/expectedError /tmp/error
}

testFailMixedVariables() {
   rm -f /tmp/variables /tmp/expectedError /tmp/error
   cat << EOF > /tmp/variables
S3_SECRET_KEY=MySecretKey
DATABASE_USER=dbuser
DATABASE_PASSWD=mysecret
DATABASE_PORT=3307
DATABASE_HOST=localhost
EOF

   cat << EOF > /tmp/expectedError
Error: The following variables has to have value: s3-access-key, database-name. Please set a valid value for it.
EOF
    ./nextcloud_backups_aws_s3  --config-file="/tmp/variables" 2> /tmp/error > /dev/null
    sed  's/^.*nextcloud_backups_aws_s3: //' -i /tmp/error
    diff /tmp/expectedError /tmp/error
    match=$?
    assertEquals "$match" "0"
    rm -f /tmp/variables /tmp/expectedError /tmp/error
}

# Load shUnit2.
. /usr/bin/shunit2
