#!/usr/bin/env bash
# file: tests/04-unsetvariables

source lib/10-set_unset_variables.sh
source lib/12-check_required_variables.sh
source lib/99-clean_variables.sh

setUp() {
    rm -f $TMP_FOLDER/variables $TMP_FOLDER/expectedError $TMP_FOLDER/error
    set_unset_variables
}

oneTimeSetUp() {
    export TMP_FOLDER="/var/tmp/nextcloudbackupsawss3/tests"
    mkdir -p $TMP_FOLDER
}

tearDown() {
    cleanVariables
    rm -f $TMP_FOLDER/*
}

testFailNoDatabaseVariables () {

   cat << EOF > $TMP_FOLDER/variables
S3_ACCESS_KEY=MyAccesKey
S3_SECRET_KEY=MySecretKey
S3_BUCKET=MyBucket
HTTP_USER=www-data
EOF

    cat << EOF > $TMP_FOLDER/expectedError
Error: The following variables has to have value: database-name, database-user, database-passwd. Please set a valid value for it.
EOF

    source $TMP_FOLDER/variables
    output=$(check_required_variables 2> $TMP_FOLDER/error)
    sed  's/^.*nextcloudbackupsawss3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?

    assertEquals "$match" "0"
}

testFailNoS3Variables() {
    cat << EOF > $TMP_FOLDER/variables
DATABASE_NAME=dbname
DATABASE_USER=dbuser
DATABASE_PASSWD=mysecret
DATABASE_PORT=3307
DATABASE_HOST=localhost
HTTP_USER=www-data
NEXTCLOUD_PATH=/test/path
NEXTCLOUD_USERS=ALL
EOF
    cat << EOF > $TMP_FOLDER/expectedError
Error: The following variables has to have value: s3-access-key, s3-secret-key, s3-bucket. Please set a valid value for it.
EOF
    source $TMP_FOLDER/variables
    output=$(check_required_variables 2> $TMP_FOLDER/error)
    sed  's/^.*nextcloudbackupsawss3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?
    assertEquals "$match" "0"
}

testNoHTTPUserVariable() {
    cat << EOF > $TMP_FOLDER/variables
S3_ACCESS_KEY=MyAccesKey
S3_SECRET_KEY=MySecretKey
S3_BUCKET=MyBucket
DATABASE_NAME=dbname
DATABASE_USER=dbuser
DATABASE_PASSWD=mysecret
DATABASE_PORT=3307
DATABASE_HOST=localhost
NEXTCLOUD_PATH=/test/path
NEXTCLOUD_USERS=ALL
EOF
#http-user is sed by default
    source $TMP_FOLDER/variables
    output=$(check_required_variables 2> $TMP_FOLDER/error)
    match=$?
    assertEquals "$match" "0"
}


testFailMixedVariables() {
    cat << EOF > $TMP_FOLDER/variables
S3_SECRET_KEY=MySecretKey
S3_BUCKET=MyBucket
DATABASE_USER=dbuser
DATABASE_PASSWD=mysecret
DATABASE_PORT=3307
DATABASE_HOST=localhost
HTTP_USER=www-data
NEXTCLOUD_PATH=/test/path
NEXTCLOUD_USERS=ALL
EOF

    cat << EOF > $TMP_FOLDER/expectedError
Error: The following variables has to have value: s3-access-key, database-name. Please set a valid value for it.
EOF

    source $TMP_FOLDER/variables
    output=$(check_required_variables 2> $TMP_FOLDER/error)
    sed  's/^.*nextcloudbackupsawss3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?
    assertEquals "$match" "0"
}

# Load shUnit2.
. /usr/bin/shunit2
