#!/usr/bin/env bash
# file: tests/04-unsetvariables

source lib/10-set_unset_database_variables.sh
source lib/12-check_required_variables.sh

setUp() {
    rm -f $TMP_FOLDER/variables $TMP_FOLDER/expectedError $TMP_FOLDER/error
    set_unset_database_variables
}

oneTimeSetUp() {
    export TMP_FOLDER="/var/tmp/nextcloud_backups_aws_s3/tests"
    mkdir -p $TMP_FOLDER
}


tearDown() {
    for var in "DATABASE_NAME DATABASE_USER DATABASE_PASSWD DATABASE_PORT DATABASE_HOST S3_ACCESS_KEY S3_SECRET_KEY S3_BUCKET"
    do
        unset $var
    done
    rm -f $TMP_FOLDER/variables $TMP_FOLDER/expectedError $TMP_FOLDER/error
}

testFailNoDatabaseVariables () {

   cat << EOF > $TMP_FOLDER/variables
S3_ACCESS_KEY=MyAccesKey
S3_SECRET_KEY=MySecretKey
S3_BUCKET=MyBucket
EOF

    cat << EOF > $TMP_FOLDER/expectedError
Error: The following variables has to have value: database-name, database-user, database-passwd. Please set a valid value for it.
EOF

    source $TMP_FOLDER/variables
    output=$(check_required_variables 2> $TMP_FOLDER/error)
    sed  's/^.*nextcloud_backups_aws_s3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?

    assertEquals "$match" "0"
}

testFailNoS3Variables() {
    cat << EOF > $TMP_FOLDER/variables
DATABASE_NAME=dbname
DATABASE_USER=dbuser
DATABASE_PASSWD=mysecret
DATABASE_PORT=3307
DATABASE_HOST=localhost
EOF
    cat << EOF > $TMP_FOLDER/expectedError
Error: The following variables has to have value: s3-access-key, s3-secret-key, s3-bucket. Please set a valid value for it.
EOF
    source $TMP_FOLDER/variables
    output=$(check_required_variables 2> $TMP_FOLDER/error)
    sed  's/^.*nextcloud_backups_aws_s3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?
    assertEquals "$match" "0"
}

testFailMixedVariables() {
    cat << EOF > $TMP_FOLDER/variables
S3_SECRET_KEY=MySecretKey
S3_BUCKET=MyBucket
DATABASE_USER=dbuser
DATABASE_PASSWD=mysecret
DATABASE_PORT=3307
DATABASE_HOST=localhost
EOF

    cat << EOF > $TMP_FOLDER/expectedError
Error: The following variables has to have value: s3-access-key, database-name. Please set a valid value for it.
EOF

    source $TMP_FOLDER/variables
    output=$(check_required_variables 2> $TMP_FOLDER/error)
    sed  's/^.*nextcloud_backups_aws_s3: //' -i $TMP_FOLDER/error
    diff $TMP_FOLDER/expectedError $TMP_FOLDER/error
    match=$?
    assertEquals "$match" "0"
}

# Load shUnit2.
. /usr/bin/shunit2
