#!/usr/bin/env bash
# file: tests/07-checkusers

source lib/15-database_backup.sh
source lib/99-clean_variables.sh

oneTimeSetUp() {
    TMP_FOLDER="/var/tmp/nextcloud_backups_aws_s3/tests"
    mkdir -p $TMP_FOLDER
}

setUp()
{
    originalPath=$PATH
    export PATH=$(pwd)/tests/stubs:$PATH
    export DATABASE_NAME="dbname"
    export DATABASE_USER="user"
    export DATABASE_PASSWD="passwdtest"
    export DATABASE_PORT=3306
    export DATABASE_HOST="127.0.0.1"
    export NEXTCLOUD_PATH=$TMP_FOLDER
    export DATABASE_BACKUP_PATH="$NEXTCLOUD_PATH/backups"
}

tearDown()
{
    export PATH=$originalPath
    rm -rf $TMP_FOLDER/*
    cleanVariables
}

testMydumperBackupFolder()
{
    MYDUMPER=$(which mydumper)
    output=$(database_backup)
    test -d $DATABASE_BACKUP_PATH
    assertEquals "$?" "0"
}

testMydumperBackupSomeTable()
{
    MYDUMPER=$(which mydumper)
    output=$(database_backup)
    test -f $DATABASE_BACKUP_PATH/table.sql.gz
    assertEquals "$?" "0"
}

# Load shUnit2.
. /usr/bin/shunit2
