#!/bin/bash

if [ ! "$2" = "-ptest" ]; then
    ( >&2 echo "ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: YES)")
    exit 1
fi

if [ $# -gt 7 ];then
    echo "cassandra george"
fi


exit 0
